import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
 import Hero from "@/components/hero";
 import Footer from "@/components/footer";
import { Import } from "lucide-react";
import Contact from "@/components/contact";
import BlogGrid from "@/components/blog";
import Cart from "@/components/cart";
import Checkout from "@/components/checkout";
import Display from "@/components/display";
import  Feature  from "@/components/feature";
import ProductListFeature from "@/components/feature";
import Insta from "@/components/insta"
import MyAccount from "@/components/Account";
import ProductGridList from "@/components/product";
import ProductpageMid from "@/components/productpageMid"

 

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        { <Navbar /> }
      < Hero />
      <Contact />
      <BlogGrid />
      <Cart />
      < Checkout />
      < Display />
     < Feature />
     <Insta />
     <MyAccount />
     < ProductGridList />
     < ProductpageMid />
      <footer />
         {children}
      </body>
    </html>
  );
}
